-- Stocki schema. Generated from the CSV header by stocki.ingest.columns;
-- tests/test_columns.py fails if this file and the data files ever disagree.
--
-- bars_raw mirrors data/<TICKER>/day<N>.csv column for column. The views below
-- are named queries, not copies -- nothing here duplicates a byte.

CREATE TABLE IF NOT EXISTS bars_raw (
    timestamp                timestamptz,
    open                     double precision,
    high                     double precision,
    low                      double precision,
    close                    double precision,
    volume                   bigint,
    dividends                double precision,
    stock_splits             double precision,
    thscode                  text,
    thsname_cn               text,
    thsname_en               text,
    currency                 text,
    hour                     smallint,
    minute                   smallint,
    ticker                   text,
    si_current_price         double precision,
    si_market_cap            double precision,
    si_pe_trailing           double precision,
    si_pe_forward            double precision,
    si_beta                  double precision,
    si_dividend_yield        double precision,
    si_dividend_rate         double precision,
    si_payout_ratio          double precision,
    si_52w_low               double precision,
    si_52w_high              double precision,
    si_employees             double precision,
    si_book_value            double precision,
    si_price_to_book         double precision,
    si_profit_margin         double precision,
    si_roa                   double precision,
    si_roe                   double precision,
    si_revenue_per_share     double precision,
    si_total_cash            double precision,
    si_total_debt            double precision,
    si_total_revenue         double precision,
    si_ebitda                double precision,
    si_gross_margins         double precision,
    si_operating_margins     double precision,
    si_debt_to_equity        double precision,
    si_quick_ratio           double precision,
    si_current_ratio         double precision,
    si_inst_pct              double precision,
    si_insider_pct           double precision,
    si_short_ratio           double precision,
    si_shares_outstanding    double precision,
    si_float_shares          double precision,
    si_target_mean           double precision,
    si_target_high           double precision,
    si_target_low            double precision,
    si_recommendation_mean   double precision,
    si_num_analysts          double precision,
    inc_total_revenue        double precision,
    inc_cost_of_revenue      double precision,
    inc_gross_profit         double precision,
    inc_operating_income     double precision,
    inc_net_income           double precision,
    inc_diluted_eps          double precision,
    inc_basic_eps            double precision,
    inc_rd                   double precision,
    inc_sga                  double precision,
    inc_tax_provision        double precision,
    inc_pretax_income        double precision,
    inc_ebitda               double precision,
    inc_ebit                 double precision,
    inc_norm_ebitda          double precision,
    inc_norm_income          double precision,
    inc_depreciation         double precision,
    inc_diluted_shares       double precision,
    inc_basic_shares         double precision,
    bs_total_assets          double precision,
    bs_total_liabilities     double precision,
    bs_stockholders_equity   double precision,
    bs_total_debt            double precision,
    bs_net_debt              double precision,
    bs_cash                  double precision,
    bs_cash_short_inv        double precision,
    bs_inventory             double precision,
    bs_receivables           double precision,
    bs_net_ppe               double precision,
    bs_gross_ppe             double precision,
    bs_accum_depreciation    double precision,
    bs_goodwill              double precision,
    bs_intangible_assets     double precision,
    bs_long_term_debt        double precision,
    bs_current_liabilities   double precision,
    bs_current_assets        double precision,
    bs_working_capital       double precision,
    bs_retained_earnings     double precision,
    bs_common_stock          double precision,
    bs_capital_stock         double precision,
    bs_total_equity          double precision,
    bs_tangible_book_value   double precision,
    bs_invested_capital      double precision,
    bs_total_capitalization  double precision,
    cf_operating             double precision,
    cf_free                  double precision,
    cf_capex                 double precision,
    cf_dividends_paid        double precision,
    cf_stock_repurchases     double precision,
    cf_financing             double precision,
    cf_investing             double precision,
    cf_net_change            double precision,
    cf_end_cash              double precision,
    cf_begin_cash            double precision,
    cf_stock_comp            double precision,
    cf_depreciation          double precision,
    cf_deferred_tax          double precision,
    cf_net_income_ops        double precision,
    cf_change_wc             double precision,
    cf_issuance_debt         double precision,
    cf_repayment_debt        double precision,
    rec_strong_buy           double precision,
    rec_buy                  double precision,
    rec_hold                 double precision,
    rec_sell                 double precision,
    rec_strong_sell          double precision,
    news_count               integer,
    news_latest_headline     text,
    day                      smallint,
    source_file              text,
    ingested_at              timestamptz,
    PRIMARY KEY (ticker, timestamp)
);

CREATE INDEX IF NOT EXISTS bars_raw_ticker_day_idx ON bars_raw (ticker, day);
CREATE INDEX IF NOT EXISTS bars_raw_timestamp_idx  ON bars_raw (timestamp);

-- The OHLCV time series the dataset loaders read.
CREATE OR REPLACE VIEW v_bars AS
SELECT ticker, day, timestamp, open, high, low, close, volume
FROM bars_raw;

-- One row per (ticker, day) instead of the same values repeated 78 times.
CREATE OR REPLACE VIEW v_fundamentals AS
SELECT DISTINCT ON (ticker, day)
    ticker,
    day,
    thscode,
    thsname_cn,
    thsname_en,
    currency,
    si_current_price,
    si_market_cap,
    si_pe_trailing,
    si_pe_forward,
    si_beta,
    si_dividend_yield,
    si_dividend_rate,
    si_payout_ratio,
    si_52w_low,
    si_52w_high,
    si_employees,
    si_book_value,
    si_price_to_book,
    si_profit_margin,
    si_roa,
    si_roe,
    si_revenue_per_share,
    si_total_cash,
    si_total_debt,
    si_total_revenue,
    si_ebitda,
    si_gross_margins,
    si_operating_margins,
    si_debt_to_equity,
    si_quick_ratio,
    si_current_ratio,
    si_inst_pct,
    si_insider_pct,
    si_short_ratio,
    si_shares_outstanding,
    si_float_shares,
    si_target_mean,
    si_target_high,
    si_target_low,
    si_recommendation_mean,
    si_num_analysts,
    inc_total_revenue,
    inc_cost_of_revenue,
    inc_gross_profit,
    inc_operating_income,
    inc_net_income,
    inc_diluted_eps,
    inc_basic_eps,
    inc_rd,
    inc_sga,
    inc_tax_provision,
    inc_pretax_income,
    inc_ebitda,
    inc_ebit,
    inc_norm_ebitda,
    inc_norm_income,
    inc_depreciation,
    inc_diluted_shares,
    inc_basic_shares,
    bs_total_assets,
    bs_total_liabilities,
    bs_stockholders_equity,
    bs_total_debt,
    bs_net_debt,
    bs_cash,
    bs_cash_short_inv,
    bs_inventory,
    bs_receivables,
    bs_net_ppe,
    bs_gross_ppe,
    bs_accum_depreciation,
    bs_goodwill,
    bs_intangible_assets,
    bs_long_term_debt,
    bs_current_liabilities,
    bs_current_assets,
    bs_working_capital,
    bs_retained_earnings,
    bs_common_stock,
    bs_capital_stock,
    bs_total_equity,
    bs_tangible_book_value,
    bs_invested_capital,
    bs_total_capitalization,
    cf_operating,
    cf_free,
    cf_capex,
    cf_dividends_paid,
    cf_stock_repurchases,
    cf_financing,
    cf_investing,
    cf_net_change,
    cf_end_cash,
    cf_begin_cash,
    cf_stock_comp,
    cf_depreciation,
    cf_deferred_tax,
    cf_net_income_ops,
    cf_change_wc,
    cf_issuance_debt,
    cf_repayment_debt,
    rec_strong_buy,
    rec_buy,
    rec_hold,
    rec_sell,
    rec_strong_sell
FROM bars_raw
ORDER BY ticker, day, timestamp;

CREATE OR REPLACE VIEW v_news AS
SELECT DISTINCT ON (ticker, day)
    ticker,
    day,
    news_count,
    news_latest_headline
FROM bars_raw
ORDER BY ticker, day, timestamp;

-- Which (ticker, day) sessions actually exist. This is where the AAPL and MSFT
-- gaps show up as data rather than as a surprise halfway through training.
CREATE OR REPLACE VIEW v_coverage AS
SELECT
    ticker,
    day,
    COUNT(*)         AS bar_count,
    MIN(timestamp)   AS first_bar,
    MAX(timestamp)   AS last_bar
FROM bars_raw
GROUP BY ticker, day
ORDER BY ticker, day;
